import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { InferGetServerSidePropsType } from 'next'
import Data from './getdata'

const Home: NextPage = () => {
// posts will be populated at build time by getStaticProps()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          What is important to you?
        </h1>
        <Data/>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' Logan Web Houqhef'}
          <span className={styles.logo}>

          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
