import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { InferGetServerSidePropsType } from 'next'


const Home: NextPage = () => {
type Data = {}

const getServerSideProps = async () => {
  // Fetch data from external API
  const res = await fetch(`https://api.census.gov/data/2019/acs/acs1?get=NAME,B01001_001E&for=state:*&key=${process.env.CENSUS_KEY}`)
  const data: Data = await res.json()

  return {
    props: {
      data,
    },
  }
}
function Getdata({ data }: InferGetServerSidePropsType<typeof getServerSideProps>) {
  // will resolve posts to type Data
  console.log(data)
  return(
    <>
  {console.log({data})}

    Hello!
    </>
  )
}
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          What is important to you?
        </h1>
        <Getdata data={''}/>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' Logan Web Dev'}
          <span className={styles.logo}>

          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
